name:                BPS
version:             0.1.0.0
github:              "jphmrst/bps"
license:             GPL-3
license-file:        Haskell-LICENSE.txt
author:              "John Maraist"
maintainer:          "haskell-tms@maraist.org"
copyright:           "2022 John Maraist; 1986-1993 Kenneth D. Forbus, Johan de Kleer and Xerox Corporation"
category:	     "Truth maintenance"

synopsis:	     "Translations of classic Truth Maintenance Systems"
description:	     "Haskell monad transformer translations of the classic Truth Maintenance Systems of Forbus and de Kleer's _Building Problem Solvers_.  See the GitHub repository <https://github.com/jphmrst/bps/>, or the Haddock documentation."

extra-source-files:
- README.md
- ChangeLog.md
- Haskell-LICENSE.txt

dependencies:
- template-haskell
- free
- resourcet
- base         (>= 4.14.3 && < 4.15) || (>= 4.15.1 && < 4.16) || (>= 4.16.0 && < 4.17)
- mtl          >= 2.2.2 && < 2.3
- extra        >= 1.7   && < 1.8
- STMonadTrans >= 0.4.6 && < 0.5
- transformers >= 0.5   && < 0.6
- symbol       >= 0.2.4 && < 0.3

library:
  source-dirs: src/main/haskell/lib
  ghc-options:
  - -w
  - -Woverlapping-patterns
  - -Wwarnings-deprecations
  - -Wdeprecations
  - -Wdeprecated-flags
  - -Wunrecognised-pragmas
  - -Wduplicate-exports
  - -Wderiving-defaults
  - -Woverflowed-literals
  - -Wempty-enumerations
  - -Wmissing-fields
  - -Wmissing-methods
  - -Wwrong-do-bind
  - -Wtyped-holes
  - -Wdeferred-type-errors
  - -Wpartial-type-signatures
  - -Wunsupported-calling-conventions
  - -Wdodgy-foreign-imports
  - -Winline-rule-shadowing
  - -Wunsupported-llvm-version
  - -Wmissed-extra-shared-lib
  - -Wtabs
  - -Wunrecognised-warning-flags
  - -Winaccessible-code
  - -Wstar-binder
  - -Wmonomorphism-restriction
  - -Wmissing-home-modules
  - -Widentities
  - -Wpartial-fields
  - -Wmissed-specialisations
  - -Wall-missed-specialisations
  - -Wcpp-undef
  - -Wunused-packages
  - -Wunused-type-patterns
  - -Wsafe
  - -Wimplicit-lift
  - -Wmissing-kind-signatures
#  - -Wsimplifiable-class-constraints # Spurious warnings from tracing code
#  - -Wredundant-constraints          # Too much
#  - -Wimplicit-prelude               # TODO later
#  - -Wmissing-import-lists           # TODO later
#  - -Wmissing-local-signatures       # Maybe later
#  - -Wmissing-export-lists           # TODO later
#  - -Wmissing-deriving-strategies    # TODO later
#  - -Wmissing-exported-signatures    # TODO later
#  - -Wambiguous-fields 
#  - -Woperator-whitespace-ext-conflict
#  - -Wduplicate-constraints # GHC says it's redundant

executables:
  hbps:
    main:                Main.hs
    source-dirs:         src/main/haskell/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BPS
    - symbol

tests:
  BPS-test:
    main:                Spec.hs
    source-dirs:         src/test/haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BPS
    - symbol >= 0.2.4 && < 0.3
    - TLT    >= 0.1.0 && < 0.2
