name:                BPS
version:             0.1.0.0
github:              "githubuser/bps-scala"
license:             AllRightsReserved
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BPS#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- extra
- STMonadTrans >= 0.4.6

library:
  source-dirs: src/main/haskell/lib

executables:
  hbps:
    main:                Main.hs
    source-dirs:         src/main/haskell/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BPS
    - symbol

tests:
  BPS-test:
    main:                Spec.hs
    source-dirs:         src/test/haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BPS
    - HUnit
    - symbol
    - transformers
    - TLT >= 0.0.0.4  ## Remember to remove the extra-deps in
                      ## stack.yaml when TLT goes external.
